name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-and-validate:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v6

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: '24'
                  cache: 'npm'

            - name: Verify Version Integrity
              run: |
                  TAG_VERSION=${GITHUB_REF#refs/tags/v}

                  PKG_VERSION=$(node -p "require('./package.json').version")

                  echo "Git Tag Version: $TAG_VERSION"
                  echo "Package.json Version: $PKG_VERSION"

                  if [ "$TAG_VERSION" != "$PKG_VERSION" ]; then
                    echo "::error::Version mismatch! Git tag ($TAG_VERSION) does not match package.json ($PKG_VERSION)."
                    exit 1
                  fi
                  echo "Versions match. Proceeding with release."

            - name: Install Dependencies
              run: npm ci

            - name: Check Code Style (Prettier)
              run: npm run check-format

            - name: Lint Code
              run: npm run lint

            - name: Build & Minify
              run: npm run build
